import pptxgen from "pptxgenjs";

/**
 * Builds a formatted PPT document in memory and returns it as a Buffer.
 * @param {Object} data - Structured document data containing title, subtitle, and slides.
 * @returns {Promise<Buffer>}
 */
export const generatePptBuffer = async (data) => {
    const ppt = new pptxgen();

    ppt.layout = "LAYOUT_WIDE";
    ppt.author = "CortexAI";
    ppt.company = "CortexAI Engine";
    ppt.title = data.title || "Presentation";

    const bgDark = "0F0524";
    const bgHeader = "1D0B3B";
    const accentColor = "9333EA";
    const textLight = "FFFFFF";
    const bgLight = "FAFAFA";
    const textDark = "333333";
    const textMuted = "888888";

    const coverSlide = ppt.addSlide();
    coverSlide.background = { color: bgDark };

    coverSlide.addShape(ppt.ShapeType.rect, { x: 1, y: 2.2, w: 8, h: 0.05, fill: { color: accentColor } });

    coverSlide.addText(data.title || "Presentation Overview", {
        x: 1, y: 2.5, w: 8, h: 1.5,
        fontSize: 44, color: textLight, bold: true, align: "center", fontFace: "Helvetica"
    });

    if (data.subtitle) {
        coverSlide.addText(data.subtitle, {
            x: 1, y: 4.2, w: 8, h: 1,
            fontSize: 22, color: accentColor, align: "center", fontFace: "Helvetica"
        });
    }

    if (Array.isArray(data.slides)) {
        data.slides.forEach((slideData, index) => {
            const slide = ppt.addSlide();
            slide.background = { color: bgLight };

            slide.addShape(ppt.ShapeType.rect, { x: 0, y: 0, w: "100%", h: 1.2, fill: { color: bgHeader } });

            const cleanTitle = (slideData.title || "").replace(/^\d+\.\s*/, '');
            slide.addText(cleanTitle, {
                x: 0.5, y: 0.3, w: 9, h: 0.6,
                fontSize: 32, color: textLight, bold: true, fontFace: "Helvetica"
            });

            if (Array.isArray(slideData.points) && slideData.points.length > 0) {
                const bulletOptions = slideData.points.map(point => {
                    const cleanPoint = point.replace(/^[-•*]\s*/, '');
                    return {
                        text: cleanPoint,
                        options: { bullet: { color: accentColor }, color: textDark, fontSize: 18, fontFace: "Helvetica", breakLine: true }
                    };
                });

                slide.addText(bulletOptions, {
                    x: 0.5, y: 1.6, w: 9, h: 5,
                    valign: "top", margin: 10, lineSpacing: 32
                });
            }

            slide.addText(`CortexAI  |  Slide ${index + 2}`, {
                x: 0.5, y: 6.9, w: 9, h: 0.5,
                fontSize: 10, color: textMuted, align: "right", fontFace: "Helvetica"
            });
        });
    }

    const closingSlide = ppt.addSlide();
    closingSlide.background = { color: bgHeader };

    closingSlide.addText("Thank You", {
        x: 1, y: 2.8, w: 8, h: 1.5,
        fontSize: 54, color: textLight, bold: true, align: "center", fontFace: "Helvetica"
    });

    closingSlide.addText("Generated by CortexAI", {
        x: 1, y: 4.5, w: 8, h: 1,
        fontSize: 18, color: accentColor, align: "center", fontFace: "Helvetica"
    });

    return await ppt.write({ outputType: "nodebuffer" });
};