import PDFDocument from "pdfkit";

/**
 * Builds a formatted PDF document in memory and returns it as a Buffer.
 * @param {Object} data - Structured document data containing title, subtitle, and sections.
 * @returns {Promise<Buffer>}
 */
export const generatePdfBuffer = (data) => {
    return new Promise((resolve, reject) => {
        try {
            const doc = new PDFDocument({
                size: "A4",
                margins: { top: 70, bottom: 70, left: 70, right: 70 },
                bufferPages: true,
            });

            const buffers = [];
            doc.on("data", (chunk) => buffers.push(chunk));
            doc.on("end", () => resolve(Buffer.concat(buffers)));
            doc.on("error", (err) => reject(err));

            const titleColor = "#000000";
            const subtitleColor = "#333333";
            const headingColor = "#444444";
            const textColor = "#222222";
            const footerColor = "#666666";

            // Title (Centered, Large)
            if (data.title) {
                doc.fillColor(titleColor)
                    .fontSize(28)
                    .font("Helvetica")
                    .text(data.title, { align: "center" });
                doc.moveDown(0.5);
            }

            // Subtitle (Centered, Medium)
            if (data.subtitle) {
                doc.fillColor(subtitleColor)
                    .fontSize(12)
                    .font("Helvetica")
                    .text(data.subtitle, { align: "center" });
                doc.moveDown(3);
            }

            // Document Sections
            if (Array.isArray(data.sections)) {
                data.sections.forEach((section) => {
                    if (doc.y > 650) {
                        doc.addPage();
                    }

                    // Section Heading (Left-aligned, Clean, No automatic numbering)
                    if (section.heading) {
                        const cleanHeading = section.heading.replace(/^\d+\.\s*/, '');

                        doc.fillColor(headingColor)
                            .fontSize(18)
                            .font("Helvetica")
                            .text(cleanHeading, { align: "left" });
                        doc.moveDown(0.8);
                    }

                    // Section Bullet Points
                    if (Array.isArray(section.points)) {
                        section.points.forEach((point) => {
                            if (doc.y > 720) {
                                doc.addPage();
                            }

                            const cleanPoint = point.replace(/^[-•*]\s*/, '');

                            doc.fillColor(textColor)
                                .fontSize(11)
                                .font("Helvetica")
                                .text(`•  ${cleanPoint}`, {
                                    indent: 0,
                                    lineGap: 4,
                                    paragraphGap: 6,
                                });
                        });
                    }

                    doc.moveDown(1.5);
                });
            }

            // Footer
            const range = doc.bufferedPageRange();
            for (let i = range.start; i < range.start + range.count; i++) {
                doc.switchToPage(i);
                doc.fillColor(footerColor)
                    .fontSize(10)
                    .font("Helvetica")
                    .text(
                        "Generated By CortexAI",
                        0,
                        doc.page.height - 50,
                        { align: "center", width: doc.page.width }
                    );
            }

            doc.end();
        } catch (error) {
            reject(error);
        }
    });
};