import { getDesiredModel } from "../config/llm.models.js";
import { generatePptBuffer } from "../utils/generatePpt.js";
import { uploadToS3 } from "../utils/uploadToS3.js";
import { fetchFromS3 } from "../utils/fetchFromS3.js";
import { deductCredits } from "../utils/deductCredits.js";

export const pptAgent = async (state) => {
    try {
        const creditStatus = await deductCredits(state.userId, "ppt");
        if (creditStatus === 400) {
            return {
                ...state,
                aiResponse: "Sorry, you don't have enough credits to use this agent. Please top up your balance in the billing section.",
            };
        }
        await deductCredits(state.userId, "ppt");
        const llm = getDesiredModel("ppt");

        const prompt = `
        You are an expert professional presentation designer.

        The user wants to generate a PowerPoint presentation about a given topic.
        Your job is to generate the COMPLETE structural content of the presentation.
        Do NOT generate the PPT file itself.

        Return ONLY valid JSON.
        Do NOT return Markdown, explanations, or any text outside the JSON.

        Use this exact structure:

        {
        "title": "Main Presentation Title",
        "subtitle": "Informative Subtitle",
        "slides": [
            {
            "title": "Slide Title",
            "points": [
                "Detailed point 1",
                "Detailed point 2",
                "Detailed point 3"
            ]
            }
        ]
        }

        Content Guidelines:
        - Create a clear, engaging, and professional title and subtitle for the cover slide.
        - Generate exactly 5 to 8 content slides that logically cover the topic from intro to conclusion.
        - Each slide must have 3 to 5 concise, impactful bullet points.
        - STRICT: Do NOT number the slide titles (e.g., write "Market Analysis", not "1. Market Analysis").
        - STRICT: Do NOT include bullet characters (*, -, •) in the points array. Just write the plain text.
        - The content should flow logically as a professional deck. 
        - Do not include "Thank You" or "Cover" slides in the "slides" array; the system handles these automatically.
        - Do not mention that the content was generated by AI.

        Topic:
        ${state.userPrompt || ""}
        `;

        const res = await llm.invoke(prompt);
        let rawContent = res.content.trim();

        if (rawContent.startsWith("```")) {
            const match = rawContent.match(/```(?:json)?\s*([\s\S]*?)\s*```/i);
            if (match) {
                rawContent = match[1].trim();
            }
        }

        let pptData;
        try {
            pptData = JSON.parse(rawContent);
        } catch (parseError) {
            console.error("PPT Agent JSON parsing failed:", parseError, "Raw:", rawContent);
            return {
                ...state,
                aiResponse: "I encountered an error structuring the presentation slides. Please try requesting the PPT again.",
            };
        }

        const pptBuffer = await generatePptBuffer(pptData);
        const fileName = `presentation_${Date.now()}.pptx`;
        await uploadToS3(fileName, pptBuffer, "application/vnd.openxmlformats-officedocument.presentationml.presentation");

        const downloadUrl = await fetchFromS3(fileName);

        return {
            ...state,
            aiResponse: `### ${pptData.title}\n*${pptData.subtitle}*\n\nYour PowerPoint presentation has been generated successfully and is ready for download.\n\n[Download Presentation (.pptx)](${downloadUrl})\n\n*Note: This secure link expires in 60 minutes.*`,
        };

    } catch (error) {
        console.error("PPT agent error:", error);
        return {
            ...state,
            aiResponse: "Sorry, I encountered an issue generating your PowerPoint presentation. Please try again.",
        };
    }
};